### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by HaxorGaruda** [bastienjalbert/topguw2#3]
how to compile or make this code be .jar file ? thanks

**Comment by bastienjalbert** [comment]
Hello,

Topguw 2 is currently in development, so you can't use it.
However you can compile the code if you add the topguw-api which is a needed library for topguw2 works correctly.

Cordially.

**Comment by HaxorGaruda** [comment]
can you how to add and compile that code ? i am not familiar with java.. but i need this program for my rtl sdr... thanks....
