### ISSUE TITLE
when topguw2 is ready for gr-gsm?

### ISSUE THREAD

**Issue by stackprogramer** [bastienjalbert/topguw2#4]
hi, i had some question,topguw1 can work with gr-gsm???
when topguw2 will be ready for using?
thanks

**Comment by bastienjalbert** [comment]
Hello,

Topguw 1 works only with airprobe.
Topguw 2 development is currently stopped because I don't have much time to work on this projet and I never receive any help .... and there is a lot of stuff to do...

Cordially

Bastien

**Comment by stackprogramer** [comment]
hi, thanks for reply,but in topguw older version  with gr-gsm i capture file cfile truely.but for cracking key stream it has not response ....

**Comment by bastienjalbert** [comment]
Yes the first version was made for my situation (French GSM network, my phone specs, ... etc), so it's normal if you can't get any results. This is why I choose to made a better version (2) but development still stopped ...
