### ISSUE TITLE
which alogorithm topguw2 uses for cracking gsm??

### ISSUE THREAD

**Issue by stackprogramer** [bastienjalbert/topguw2#5]
hi, topguw 2 is not updated any. i want to create a cracking gsm with gnuradio grc environment  based gr-gsm, can you guide me for algorithm that you are using for cracking gsm?
thank you
 best regards stackprogramer

**Comment by bastienjalbert** [comment]
Hi,

Why dont use Topguw api to work with Java? Or continue Topguw2 development :-)

You can see the Karsten Nohl conference to understand all steps to crack GSM, I can help you at need but I didn't work on this since a long time ...

Cordially

**Comment by stackprogramer** [comment]
thanks for reply,i will soon study algorithm,It is my pleasure to contributing in topguw2 development.
i soon will read your source java.maybe i send you comment for development in topguw2 api.
,any way thanks very much
best regards stackprogramer
