### ISSUE TITLE
in topguw gsmframecoder/test is not in last version airprobe?

### ISSUE THREAD

**Issue by stackprogramer** [bastienjalbert/topguw2#7]
hi,i finally install airprobe in ubuntu 12.04 and i run topguw,the path gsmframecoder/test is not in airprobe folder?do you mean gsmdecode folder ?
thank you best regards stackprogramer

**Comment by stackprogramer** [comment]
hi again, can you share a cfile that is tested and find key stream on topguw1,
i uses this cfile can not detect wget ​https://svn.berlin.ccc.de/projects/airprobe/raw-attachment/wiki/DeModulation/capture_941.8M_112.cfile

in airprobe  i can not capture cfile  with device rtl-sdr,i should use other way.
thank you

**Comment by bastienjalbert** [comment]
Hi, maybe you should change the decimal rate (112 or 64 or another value),
I remember that when I changed this value, some results was better.

I'm sorry but I don't have any cfile right now.

Cordially.

2016-11-19 8:00 GMT+01:00 R.B notifications@github.com:

**Comment by stackprogramer** [comment]
thanks for reply and guidance
best regards stackprogramer
